marvel_avatar/models.py
from datetime import datetime
from flask_login import UserMixin,LoginManager
from flask_sqlalchemy import SQLAlchemy
from flask_marshmallow import Marshmallow
import uuid


db = SQLAlchemy()
ma = Marshmallow()
login_manager = LoginManager()

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)

class User(UserMixin, db.Model):
    id = db.Column(db.String(36), primary_key=True, default=str(uuid.uuid4()))
    name = db.Column(db.String(50), nullable=False)
    email = db.Column(db.String(120), unique=True, nullable=False)
    password = db.Column(db.String(128), nullable=False)
    token = db.Column(db.String(128), unique=True, nullable=False)
    date_created = db.Column(db.DateTime, default=datetime.utcnow)
    characters = db.relationship('MarvelCharacter', backref='user', lazy=True)

class MarvelCharacter(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100), nullable=False)
    description = db.Column(db.String(500), nullable=True)
    comics = db.Column(db.String(10000), nullable=True)
    super_power = db.Column(db.String(100), nullable=True)
    image = db.Column(db.String(255), nullable=True)
    date_created = db.Column(db.DateTime, default=datetime.utcnow)
    user_token = db.Column(db.String(128), db.ForeignKey('user.token'), nullable=False)

marvel_avatar/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, IntegerField, TextAreaField
from wtforms.validators import DataRequired, Email, EqualTo, ValidationError
from .models import User

class RegistrationForm(FlaskForm):
    name = StringField('Name', validators=[DataRequired()])
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    confirm_password = PasswordField('Confirm Password', validators=[DataRequired(), EqualTo('password')])
    submit = SubmitField('Sign Up')

    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user:
            raise ValidationError('Email already in use. Please choose a different one.')

class LoginForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    submit = SubmitField('Log In')

class MarvelCharacterForm(FlaskForm):
    name = StringField('Name', validators=[DataRequired()])
    description = TextAreaField('Description', validators=[DataRequired()])
    comics_appeared_in = IntegerField('Comics Appeared In', validators=[DataRequired()])
    super_power = StringField('Super Power', validators=[DataRequired()])
    submit = SubmitField('Add Character')

marvel_avatar/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_marshmallow import Marshmallow
from flask_migrate import Migrate
from flask_login import LoginManager
from .api.routes import api
from .authentication.routes import auth
from .site.routes import site
from .models import db as root_db, login_manager, ma 
from config import Config
from .helpers import to_est, JSONEncoder
import os
from dotenv import load_dotenv

from flask_cors import CORS

load_dotenv()

app = Flask(__name__)
app.secret_key = "12345"



@app.context_processor
def inject_to_est():
    return {'to_est': to_est}

app.register_blueprint(api)
app.register_blueprint(site)
app.register_blueprint(auth)

app.config.from_object(Config)
root_db.init_app(app)

migrate = Migrate(app, root_db)

ma.init_app(app)

login_manager.init_app(app)
login_manager.login_view = 'auth.login'

app.json_encoder = JSONEncoder


CORS(app)

marvel_avatar/api/routes.py
from flask import Blueprint,request, jsonify
from marvel_avatar.models import db, MarvelCharacter
from flask_login import login_required, current_user

api = Blueprint('api', __name__, url_prefix='/api')


@api.route('/add_character', methods=['POST'])
@login_required
def add_character():
    character_data = request.json
    new_character = MarvelCharacter(
        name=character_data['name'],
        description=character_data['description'],
        comics=character_data['comics'],
        image=character_data["image"],
        user_token=current_user.token,
    )

    try:
        db.session.add(new_character)
        db.session.commit()
        return jsonify(success=True)
    except:
        db.session.rollback()
        return jsonify(success=False)
    
    
@api.route('/delete_character/<int:character_id>', methods=['DELETE'])
@login_required
def delete_character(character_id):
    character = MarvelCharacter.query.filter_by(id=character_id, user_token=current_user.token).first()
    if character:
        try:
            db.session.delete(character)
            db.session.commit()
            return jsonify(success=True)
        except:
            db.session.rollback()
            return jsonify(success=False)
    else:
        return jsonify(success=False)

marvel_avatar/authentication/routes.py
from flask import Blueprint, render_template, url_for, redirect, request, jsonify, flash
from marvel_avatar.models import db, User, MarvelCharacter
from marvel_avatar.forms import LoginForm, RegistrationForm, MarvelCharacterForm
from flask_login import login_user, logout_user, login_required, current_user
from werkzeug.security import generate_password_hash, check_password_hash
import hashlib
import os

auth = Blueprint('auth', __name__, template_folder='auth_templates')


@auth.route('/register', methods=['GET', 'POST'])
def register():
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = generate_password_hash(form.password.data, method='sha256')
        new_user = User(name=form.name.data, email=form.email.data, password=hashed_password)
        new_user.token = hashlib.sha256(os.urandom(60)).hexdigest()
        db.session.add(new_user)
        db.session.commit()
        return redirect(url_for('auth.login'))
    return render_template('register.html', form=form)

@auth.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and check_password_hash(user.password, form.password.data):
            login_user(user)
            return redirect(url_for('site.home'))
        else:
            flash('Invalid email or password', 'danger')
    return render_template('login.html', form=form)

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('site.home'))

marvel_avatar/site/routes.py
from flask import Blueprint, render_template, url_for, redirect, request, jsonify, flash
from marvel_avatar.models import db,User, MarvelCharacter
from flask_login import login_user, logout_user, login_required, current_user

site = Blueprint('site', __name__, template_folder='site_templates')


@site.route('/')
@login_required
def home():
    profile = MarvelCharacter.query.filter_by(user_token=current_user.token).all()
    return render_template('home.html', profile=profile)


@site.route('/profile')
@login_required
def profile():
    characters = MarvelCharacter.query.filter_by(user_token=current_user.token).all()
    return render_template('profile.html', characters=characters)

marvel_avatar/templates/base.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<!-- Required meta tags -->
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />

		<!-- Bootstrap CSS -->

		<link
			href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css"
			rel="stylesheet"
		/>
		<link
			href="https://getbootstrap.com/docs/5.3/assets/css/docs.css"
			rel="stylesheet"
		/>
		<!-- Google Font -->
		<link
			href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;600&display=swap"
			rel="stylesheet"
		/>
		<!-- CSS -->
		<link rel="stylesheet" href="../static/css/main.css" />
		<title>Marvel Avatars</title>
		<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"></script>
	</head>
	<body>
		<!-- Navbar -->

		<nav class="navbar navbar-expand-lg bg-body-tertiary mb-4">
			<div class="container-fluid">
				<a class="navbar-brand" href="{{ url_for('site.home') }}"
					>Marvel Avatars</a
				>
				<button
					class="navbar-toggler"
					type="button"
					data-bs-toggle="collapse"
					data-bs-target="#navbarSupportedContent"
					aria-controls="navbarSupportedContent"
					aria-expanded="false"
					aria-label="Toggle navigation"
				>
					<span class="navbar-toggler-icon"></span>
				</button>
				<div
					class="collapse navbar-collapse"
					id="navbarSupportedContent"
				>
					<ul class="navbar-nav me-auto mb-2 mb-lg-0">
						<li class="nav-item">
							<a
								class="nav-link {% block home_active %}{% endblock %}"
								aria-current="page"
								href="{{ url_for('site.home') }}"
								>Home</a
							>
						</li>
					</ul>
					<div class="d-flex">
						{% if current_user.is_authenticated %}
						<a
							href="{{ url_for('site.profile') }}"
							class="btn btn-info mx-3"
						>
							Profile </a
						><a
							href="{{ url_for('auth.logout') }}"
							class="btn btn-warning"
						>
							Logout
						</a>

						{% else %}
						<a
							href="{{ url_for('auth.login') }}"
							class="btn btn-primary mx-3"
						>
							Login
						</a>
						<a
							href="{{ url_for('auth.register') }}"
							class="btn btn-info"
						>
							Register
						</a>
						{% endif %}
					</div>
				</div>
			</div>
		</nav>

		<!-- joke,images,users,login and signup content -->

		{% block content %} {% endblock %}



		<!-- Optional JavaScript -->
		<!-- jQuery first, then Popper.js, then Bootstrap JS -->
		<script src="../static/js/script.js"></script>
		<script
			src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
			integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
			crossorigin="anonymous"
		></script>
		<script
			src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js"
			integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
			crossorigin="anonymous"
		></script>
		<script
			src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js"
			integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
			crossorigin="anonymous"
		></script>
	</body>
</html>